from __future__ import annotations


def render_readme(bundle_name: str, industry: str, row_counts: dict[str, int], scenario_names: list[str]) -> str:
    total_rows = sum(row_counts.values())
    scenario_line = ", ".join(scenario_names) if scenario_names else "(none)"
    rows_table = "\n".join(f"| `{t}` | {n:,} |" for t, n in row_counts.items())
    return f"""# {bundle_name}

Synthetic procurement dataset generated by the **Procurement Data Simulator**.

- **Industry profile**: `{industry}`
- **Scenarios applied (in order)**: {scenario_line}
- **Total rows (all tables)**: {total_rows:,}

## Contents

```
{bundle_name}/
├── data/                       CSV tables (one per entity)
├── dataset.xlsx                Multi-sheet workbook (same tables)
├── dataset.sqlite              SQLite DB with FKs intact
├── recipe.yaml                 Reproducible recipe (profile + scenarios + seed)
├── manifest.json               Generator version, timestamps, SHA256 per file
├── data_dictionary.md          Every column explained
├── sample_queries.sql          10 ready-to-run queries against dataset.sqlite
└── README.md                   This file
```

## Row counts

| Table | Rows |
| --- | ---: |
{rows_table}

## Loading the data

### pandas

```python
import pandas as pd
suppliers = pd.read_csv("data/suppliers.csv")
transactions = pd.read_csv("data/transactions.csv", parse_dates=["date"])
```

### SQLite (queryable immediately, FKs intact)

```bash
sqlite3 dataset.sqlite < sample_queries.sql
```

### Excel

Open `dataset.xlsx` — every table is a sheet.

### Postgres

```bash
sqlite3 dataset.sqlite .dump | psql your_database
```

### Power BI

Point Power BI at `dataset.sqlite` via an ODBC connector, or load the CSVs directly.

## Reproducibility

This bundle is fully reproducible. Anyone with `recipe.yaml` and the simulator source
can regenerate byte-identical output:

```bash
python -m procurement_simulator.cli generate --recipe recipe.yaml --out ./out.zip
```

The `manifest.json` file records SHA256 hashes for every artifact so you can verify integrity.
"""
